dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh |
  bash
notifications:
  slack:
    secure: nNJN9Gs7Rp9zTissP2/wJsWp98MkO0IzHAkdPqcMzF7ZS+HOL21kxaHDi2ZM92p6LV1LGsIkr+7Uhc9bcVJ+HJTTIQoN/WUv3O5C7i0+Kb4fyqGmWDHTDEO2Y+I0vDilj75Qh4lJPtOfbw7IwUy52cvHldT7wHJr7FR5yyCbKA+t6m0N6f0purURkAppf+KviTujs99UNvhL6mAoNtrSheMIaDJyUus2AdvkW/9RiAh/fyd2msuDFoui73x+8ntTE8KqLCWji78jk3PmOUIT6Sk0yXniwX7dbsf5Gfl8u/y5ymSi/4ztDmFZGCHs3lEskthwDLSj3Hxyf+nK8ari4nDnU+yqWcx0OsdrOLF5k1hiFALrS4H79E77pG7rU2B6dxTiUOsL0g72dPb/0mcb/lWTMSJuBio+Oh18oQDEI5FOb2uEiHM0AxmnO6decRBM1g9Gdy4ob83RUugBLVONF398MEbnEIkQq8ZhG7lniUZJpPK6HTELZ+HKPdFjaOiu8M9tQeUKrXc2CJaCXT607olehdaMYFI3sOHxlw6lmyyn2vWKkXA34Vw9vVWAOoN2H3v72VZBisM9VPHmLjWOr1yyvKMR+lmcYfzmfiRkUlEeP2SJcAWSJXBJhhTGilX80uE/gyhYXdAhUjK7JNpv0OblMLWybvC4zu3JM9UFPOI=
