---
- name: Configure app server
  hosts: app
  become: true
  vars:
    db_host: 10.132.0.2
  tasks:
    - name: Ensures ruby installed
      apt:
        name: "{{ package }}"
        state: present
        update_cache: true
      with_items:
        - ruby-full
        - ruby-bundler
        - build-essential
      loop_control:
        loop_var: package

    - name: Add unit file for Puma
      copy:
        src: puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Enable puma
      become: true
      systemd:
        name: puma
        enabled: true

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config

  handlers:
  - name: reload puma
    become: true
    systemd:
      name: puma
      state: restarted
